### ISSUE TITLE
対策のお願い。

### ISSUE THREAD

**Issue by SoratobuMacaroniPenguin** [FaBoPlatform/DonkeyDocs#1]
先日、荷物が届き、早速今日から組み立て始めている者です。
初心者にもとってもわかりやすいチュートリアルありがとうございます。
ただ、気になったことをここに書きます。
１．「教師データ」の作成で「python manage.py drive --js」を実行したのですが、エラーが発生して先に進めませんでした。そこで詳しくはわからなったのですが、カメラがエラーが出ているらしいとこから「motion」と「 libjpeg62」をインストールすることでカメラのエラーは出なくなりました。どちらが原因だったのかはわかりません。
２．現在は別のエラーが出ているのですが、エラーの意味がわからずこの先に進むことができずに困っています。出ているエラーは
using donkey version: 2.5.8 ...
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    import donkeycar as dk
  File "/home/pi/env/lib/python3.5/site-packages/donkeycar/__init__.py", line 21, in <module>
    from . import util
  File "/home/pi/env/lib/python3.5/site-packages/donkeycar/util/__init__.py", line 1, in <module>
    from . import (proc,
  File "/home/pi/env/lib/python3.5/site-packages/donkeycar/util/img.py", line 6, in <module>
    from PIL import Image
  File "/home/pi/env/lib/python3.5/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
３．Donkey Carの興味のある人たちが知識を共有できる掲示板（ＢＢＳ？）などはありませんか？　または作る予定はありませんか？
４．まだ先になるとは思うのですが、今後Donkey Carをアレンジしていくにあたって、提供していただいたイメージディスクに関して、オリジナルのRaspbianからどのようなアレンジをしたものなのか教えていただくことはできませんでしょうか。

７月１６日のハンズオンまでにはある程度進めておきたいと思っています。お手数をおかけします。よろしくお願いいたします。

**Comment by akira-sasaki** [comment]
> １．「教師データ」の作成で「python manage.py drive --js」を実行したのですが、エラーが発生して先に進めませんでした。そこで詳しくはわからなったのですが、カメラがエラーが出ているらしいとこから「motion」と「 libjpeg62」をインストールすることでカメラのエラーは出なくなりました。どちらが原因だったのかはわかりません。

カメラ不良の可能性もありますので、再度カメラを郵送いたします。

> ２．現在は別のエラーが出ているのですが、エラーの意味がわからずこの先に進むことができずに困っています。出ているエラーは
using donkey version: 2.5.8 ...
Traceback (most recent call last):

こちらも原因がわからないので、新しくおくるカメラで確認の方をお願いできませんでしょうか？

>３．Donkey Carの興味のある人たちが知識を共有できる掲示板（ＢＢＳ？）などはありませんか？　または作る予定はありませんか？

Facebookになりますが、AIでRCカーを走らせよう！というコミュニティがあります。
https://www.facebook.com/groups/2249059025382644/

> ４．まだ先になるとは思うのですが、今後Donkey Carをアレンジしていくにあたって、提供していただいたイメージディスクに関して、オリジナルのRaspbianからどのようなアレンジをしたものなのか教えていただくことはできませんでしょうか。

https://faboplatform.github.io/DonkeyDocs/0.DonkeyCar%E3%81%AE%E6%A7%8B%E7%AF%89/02.rasppi_allsetting/

この項目にベースのイメージに追加した処理を記載しています。

**Comment by naisy** [comment]
問題が継続しているようでしたら再度openしてください。
Please reopen this if the problem continues.
