### ISSUE TITLE
Updated Tensorflow-bin repository

### ISSUE THREAD

**Issue by PINTO0309** [FaBoPlatform/DonkeyDocs#2]
I am the creator of **[PINTO0309/Tensorflow-bin](https://github.com/PINTO0309/Tensorflow-bin)**.

As the repository grew, I replaced tensorflow-2.0.0a0-cp35-cp35m-linux_armv7l.whl with a new version of tensorflow-2.0.0b1-cp35-cp35m-linux_armv7l.whl. Therefore, the steps in the following article you created will not work.

- TensorFlow 2.0.0-Alpha0をwgetコマンドで取得します。
- TensorFlow 2.0.0-Alpha0をインストールします。
https://faboplatform.github.io/DonkeyDocs/2.DonkeyCar%E5%80%8B%E5%88%A5%E8%A8%AD%E5%AE%9A/03.install/

I recommend replacing with 
`https://github.com/PINTO0309/Tensorflow-bin/raw/master/tensorflow-2.0.0b1-cp35-cp35m-linux_armv7l.whl`
or
`https://github.com/PINTO0309/Tensorflow-bin/raw/master/tensorflow-2.0.0b1-cp37-cp37m-linux_armv7l.whl`
or
`https://github.com/PINTO0309/Tensorflow-bin/raw/master/tensorflow-2.0.0rc0-cp37-cp37m-linux_armv7l.whl`.

**Comment by akira-sasaki** [comment]
Thank you for the update information.
I updated our documents.
https://faboplatform.github.io/DonkeyDocs/2.DonkeyCar%E5%80%8B%E5%88%A5%E8%A8%AD%E5%AE%9A/03.install/
https://faboplatform.github.io/DonkeyDocs/2.DonkeyCar%E5%80%8B%E5%88%A5%E8%A8%AD%E5%AE%9A/03.install3_0_2/

And, thank you for your effort of providing latest tensor flow package.

**Comment by PINTO0309** [comment]
Thank you for your quick response. I intend to build the latest package for a while.
